### ISSUE TITLE
Taking only uppercase codes

### ISSUE THREAD

**Issue by pstatonwx** [liamcryan/airporttime#3]
Recommend adding a ".upper()" to the function call - the function breaks if a user enters a mixed case airport code.

**Comment by liamcryan** [comment]
Yea, that sounds like a good idea.  

Maybe here: https://github.com/liamcryan/airporttime/blob/master/airporttime/__init__.py#L65

Or here: https://github.com/liamcryan/airporttime/blob/master/airporttime/__init__.py#L52

Or even here: https://github.com/liamcryan/airporttime/blob/master/airporttime/__init__.py#L23

Which makes more sense?  Probably the lower level is better...line 23...

Also, probably should enforce kwargs:
`
class AirportTime(object):
    def __init__(self, *, iata_code: Optional[str] = None, icao_code: Optional[str] = None):
        ...
`

What are you using the library for?

**Comment by pstatonwx** [comment]
Line 23 should work! Thanks!

I'm making a weather tool and just need to present the user with local times rather than UTC times - really appreciate all your hard work!

**Comment by pstatonwx** [comment]
This is a very popular list for us meteorologists! It seems there might be a few missing - what information would you need to implement them in this package?

https://www.cnrfc.noaa.gov/metar.php

**Comment by liamcryan** [comment]
Minimally, something like:
  observation station identifier: PADK (how you will identify the station)
  timezone: '<PADK timezone>' (pytz time zone - see example format in README)

Generically if you had a csv file with at least these two columns, you could generalize this package to instead of airporttime, maybe call it stationtz, which could handle conversion by airport station code or meteorological station.

The time zone conversions are mostly handled by pytz.  Obtain the timezone for each station and you can use this approach.  I once thought of trying to use GPS coordinates to identify the time zone, but the data I ended up using already included it.

**Comment by pstatonwx** [comment]
Okay thanks so much!

**Comment by pstatonwx** [comment]
Hey Liam, noticed this issue is still open - was the intention for me to provide you with the stations/timezones I needed to be implemented in this package? Just checking, thank you! :)

**Comment by liamcryan** [comment]
This organization assembles the file I am using:  https://github.com/opentraveldata/opentraveldata/tree/master/opentraveldata (optd_por_public.csv).

I could help with the implementation but the hard part might be finding a source of data.  I'm not familiar with the data you are interested in - there seems to be overlap in the data you linked earlier and airline stations, but I suppose there will be a lot of meteorological stations that are not also airline stations?

**Comment by pstatonwx** [comment]
Okay! Yeah any help getting these weather stations added would be awesome. I would do everything I can on my end to give you the info you needed. 

For example, if a user calls "KNYC," my tool will break because that specific icao code isn't in that CSV file that airporttime pulls from. The list I linked above has a combination of meteorological stations and airports (sometimes an airport has it's own meteorology station) that I am interested in. 

What I can do is go through and ping every station my list that I need, and gather a list of stations that are missing, accompanied with their needed time zone - would that help?

**Comment by liamcryan** [comment]
Maybe instead, I could provide a way for the library to set your own station...something like:

```
knyc= airporttime.create_station(**{"iata": "KNYC", "timezone": "<your time zone>"})
# then you can use to_utc & from_utc normally
knyc.to_utc
knyc.from_utc
```

This would let you fill in the blanks rather than customizing the list on my end.

Here you can see how the timezone should be formatted.
```
import pytz
pytz.all_timezones
```

**Comment by pstatonwx** [comment]
That would be perfect! Thanks Liam!

**Comment by pstatonwx** [comment]
Solved! I found that I can pull the timezones from here: https://www.weather.gov/zse/InfoPIL?id=<icao_code_here>

Thank you!

**Comment by liamcryan** [comment]
Nice - I'll try to look at this tonight...

**Comment by pstatonwx** [comment]
Sorry to keep blowing this up! But better yet, the National Weather Service has an api that would also be useful: 
https://api.weather.gov/stations?id=<icao_code_here>

No need to add onto your library now if you don't want to!

**Comment by liamcryan** [comment]
All right, so I just made some changes 581c1d6cce35423285d2f58f1cc4b2c082d53d04

I think you can try it out with the command below, but your existing code will need to be modified:
```
pip install git+https://github.com/liamcryan/airporttime.git
```

I wrote a little bit on the README about how to go about specifying your own stations.

**Comment by pstatonwx** [comment]
Okay thanks so much! This is probably good to close now - I appreciate it!
